# Generated by Django 3.1.1 on 2020-11-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='melakarta',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
