# Generated by Django 3.1.1 on 2020-12-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragas', '0002_melakarta_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='raga',
            name='mela_true',
            field=models.BooleanField(default=False),
        ),
    ]
