# Generated by Django 4.2.11 on 2026-03-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ragas', '0003_raga_mela_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagaEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0, help_text='Jaccard similarity between 0 and 1')),
                ('shared_notes', models.IntegerField(default=0, help_text='Number of shared notes')),
                ('total_notes', models.IntegerField(default=0, help_text='Total unique notes in union')),
                ('source_raga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='ragas.raga')),
                ('target_raga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='ragas.raga')),
            ],
            options={
                'ordering': ['-similarity_score'],
                'unique_together': {('source_raga', 'target_raga')},
            },
        ),
    ]
