# Generated by Django 6.0.3 on 2026-03-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragas', '0004_ragaedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='raga',
            name='embedding',
            field=models.TextField(blank=True, help_text='ML-generated embedding vector stored as JSON', null=True),
        ),
        migrations.AlterField(
            model_name='melakarta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='raga',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ragaedge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
