# Generated by Django 3.1.1 on 2020-12-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('angas', models.CharField(max_length=512)),
                ('aksharas', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=128)),
            ],
        ),
    ]
