# Generated by Django 3.1.1 on 2020-12-09 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='tala',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talas.talacategory'),
        ),
    ]
